spring:
  application.name: kafka-streams
  kafka:
    bootstrap-servers: http://localhost:29092
    properties:
      schema.registry.url: http://localhost:8081
      auto.register.schemas: false
    streams:
      application-id: vehicle-kafka-streams
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
        default.value.serde: io.confluent.kafka.streams.serdes.json.KafkaJsonSchemaSerde
        json.value.type: com.epam.schema.Coordinate