spring:
  main:
    web-application-type: none
  kafka:
    producer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

output-topic: testOutput
input-topic: testInput

input-coordinate-data-format: com.epam.consumer.model.Coordinate