spring:
  application:
    name: producer
  kafka:
    bootstrap-servers: http://localhost:29092
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
      properties:
        #use.schema.id: 1000
        #use.latest.version: true
        auto.register.schemas: false

server.port: 8090
logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %X{CorrelationId} %logger{36} - %msg%n"
anyvariable: ENC(F3H2XSOsno235Hjq99a/gGydzT1Qg+iNbSZrHG4bvh6sNV5qT/3C3vvdtkFTdHbs)
jasypt:
  encryptor:
    password: ${ENCRYPTION_KEY}
